name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install jq JSON processor
      run: sudo apt-get install jq
    - name: validates talks.json
      run: jq '.' talks.json
